### PR TITLE
cutoutEntity and workflow documentation

### PR DESCRIPTION
**Pull request by kfarr**
This addresses #16 and #17, however it does introduce 2 new .splat files in the repo instead of the train model hosted on huggingface to show off the workflow as well as cutout. We can revert to the train splat instead if desired.

### CODE REVIEW

**Comment by kfarr** [comment]
Maybe I can move this new demo in index.html to a glitch project and then that file can remain unchanged and we don't need to add the splat files

**Comment by quadjr** [comment]
Thank you for your pull request.
I've uploaded your splat files to HuggingFace.
You can use the following URLs to access the model:
https://huggingface.co/quadjr/aframe-gaussian-splatting/resolve/main/luma-seal.splat
https://huggingface.co/quadjr/aframe-gaussian-splatting/resolve/main/polycam-seal.splat

To integrate the cutout demo into the main repository, how about creating a new HTML file named "cutout_demo.html" and adding a link to it in the README?

**Comment by kfarr** [comment]
ok updated!

**Comment by quadjr** [comment]
Great! I've merged!

**Pull request merged**
